services:
  - type: web
    name: buggu-md
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGO_URI
        sync: false
      - key: OWNER_NUMBER
        sync: false
      - key: PREFIX
        sync: false
      - key: MODE
        sync: false
      - key: OPENAI_API_KEY
        sync: false
    healthCheckPath: /health
    autoDeploy: true
